services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566" 
    environment:
      - SERVICES=s3  
      - AWS_SECRET_ACCESS_KEY = "test"  
      - AWS_ACCESS_KEY_ID = "test" 
      - AWS_SECRET_ACCESS_KEY = "test"
      - AWS_S3_ENDPOINT = "http://localhost:4566"
    volumes:
      - "./localstack_data:/var/lib/localstack" 
